const IDENTIFIER = "@@favoriteVideos/";

export const ADD_FAVORITE_REQUEST = `${IDENTIFIER}ADD_FAVORITE_REQUEST`;
export const ADD_FAVORITE_SUCCESS = `${IDENTIFIER}ADD_FAVORITE_SUCCESS`;
export const ADD_FAVORITE_FAILURE = `${IDENTIFIER}ADD_FAVORITE_FAILURE`;

export const TOGGLE_FAVORITE_REQUEST = `${IDENTIFIER}TOGGLE_FAVORITE_REQUEST`;
export const TOGGLE_FAVORITE_SUCCESS = `${IDENTIFIER}TOGGLE_FAVORITE_SUCCESS`;
export const TOGGLE_FAVORITE_FAILURE = `${IDENTIFIER}TOGGLE_FAVORITE_FAILURE`;

export const FETCH_FAVORITES_REQUEST = `${IDENTIFIER}FETCH_FAVORITES_REQUEST`;
export const FETCH_FAVORITES_SUCCESS = `${IDENTIFIER}FETCH_FAVORITES_SUCCESS`;
export const FETCH_FAVORITES_FAILURE = `${IDENTIFIER}FETCH_FAVORITES_FAILURE`;