const IDENTIFIER = "@@videos/";

export const FETCH_VIDEOS_REQUEST = `${IDENTIFIER}FETCH_VIDEOS_REQUEST`;
export const FETCH_VIDEOS_SUCCESS = `${IDENTIFIER}FETCH_VIDEOS_SUCCESS`;
export const FETCH_VIDEOS_FAILURE = `${IDENTIFIER}FETCH_VIDEOS_FAILURE`;

export const TOGGLE_VIDEO_FAVORITE = `${IDENTIFIER}TOGGLE_VIDEO_FAVORITE`;